#!/usr/bin/env zsh

typeset -g ZSH_COMMAND_NOT_FOUND_CHECK_EXEC=${ZSH_COMMAND_NOT_FOUND_CHECK_EXEC-false}

${ZSH_COMMAND_NOT_FOUND_OPTIONS-false} || typeset -ag ZSH_COMMAND_NOT_FOUND_OPTIONS=()

${ZSH_COMMAND_NOT_FOUND_NO_FAILURE_MSG:-true} \
    && ZSH_COMMAND_NOT_FOUND_OPTIONS+=('--no-failure-msg')
${ZSH_COMMAND_NOT_FOUND_IGNORE_INSTALLED:-true} \
    && ZSH_COMMAND_NOT_FOUND_OPTIONS+=('--ignore-installed')
$ZSH_COMMAND_NOT_FOUND_DATA_DIR \
    && ZSH_COMMAND_NOT_FOUND_OPTIONS+=('-d' "$ZSH_COMMAND_NOT_FOUND_DATA_DIR")

if $ZSH_COMMAND_NOT_FOUND_CHECK_EXEC \
    && which &> /dev/null command-not-found; then
        command-not-found ${ZSH_COMMAND_NOT_FOUND_OPTIONS[@]} \
            -- ${1+"$1"}
else
    command-not-found ${ZSH_COMMAND_NOT_FOUND_OPTIONS[@]} -- ${1+"$1"}
fi
